### ISSUE TITLE
Custom template coordinate

### ISSUE THREAD

**Issue by burn2delete** [boot-clj/boot-new#21]
Use any dependency namespace for template

**Comment by seancorfield** [comment]
Currently, you can specify any group ID but the artifact ID is always fixed as `boot-template` (or `lein-template`).

I'll update this to allow a group/artifact style name which will override the `/boot-template` part.

**Comment by seancorfield** [comment]
One wrinkle in this, currently the template name is used to identify the namespace inside the template that is used to build the project: `boot.new.template-name/template-name`

If you have a multi-part template name, that will generate an illegal symbol.

I _could_ parse out the last segment of the template name and ignore any specified artifact, so `org.foobar.whatever/my-template` would map to `boot.new.whatever/whatever`, but that's seems over-complex and in fact somewhat "magic".

However, now I look at the code, I see that it first checks for `boot.new.template-name` as an available namespace so I believe (but have not tested this yet) you could do the following:

```
boot -d org.foobar.whatever/my-template -d seancorfield/boot-new new -t the-template -n app
```

and it would download the artifact and then look for `boot.new.the-template/the-template` in it, in which case, this ticket is probably not needed.

**Comment by seancorfield** [comment]
Yup, I just tested this. If you have a Boot template project -- that contains `boot.new.something/something` as the project creation function -- you can package it in a project that has _any_ coordinates, such as `org.foobar.whatever/my-template` and put that in your repo, then you can use that with:

```
boot -d org.foobar.whatever/my-template -d seancorfield/boot-new new -t something -n app
```

Boot will download the project and add it to your classpath so that `boot-new` can find it. So no changes are needed.
